// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package os2mo

import (
	"github.com/Khan/genqlient/graphql"
	"github.com/google/uuid"
)

// getITSystemsItsystemsITSystem includes the requested fields of the GraphQL type ITSystem.
// The GraphQL type's documentation follows.
//
// Systems that IT users are connected to
type getITSystemsItsystemsITSystem struct {
	// Name/titel of the itsystem.
	Name string `json:"name"`
	// The ITSystem type.
	System_type string `json:"system_type"`
	// The object type
	Type string `json:"type"`
	// Short, unique key.
	User_key string `json:"user_key"`
	// UUID to be created. Will be autogenerated if not specified.
	Uuid uuid.UUID `json:"uuid"`
}

// GetName returns getITSystemsItsystemsITSystem.Name, and is useful for accessing the field via an interface.
func (v *getITSystemsItsystemsITSystem) GetName() string { return v.Name }

// GetSystem_type returns getITSystemsItsystemsITSystem.System_type, and is useful for accessing the field via an interface.
func (v *getITSystemsItsystemsITSystem) GetSystem_type() string { return v.System_type }

// GetType returns getITSystemsItsystemsITSystem.Type, and is useful for accessing the field via an interface.
func (v *getITSystemsItsystemsITSystem) GetType() string { return v.Type }

// GetUser_key returns getITSystemsItsystemsITSystem.User_key, and is useful for accessing the field via an interface.
func (v *getITSystemsItsystemsITSystem) GetUser_key() string { return v.User_key }

// GetUuid returns getITSystemsItsystemsITSystem.Uuid, and is useful for accessing the field via an interface.
func (v *getITSystemsItsystemsITSystem) GetUuid() uuid.UUID { return v.Uuid }

// getITSystemsResponse is returned by getITSystems on success.
type getITSystemsResponse struct {
	// Get a list of all ITSystems, optionally by uuid(s)
	Itsystems []getITSystemsItsystemsITSystem `json:"itsystems"`
}

// GetItsystems returns getITSystemsResponse.Itsystems, and is useful for accessing the field via an interface.
func (v *getITSystemsResponse) GetItsystems() []getITSystemsItsystemsITSystem { return v.Itsystems }

func getITSystems(
	client graphql.Client,
) (*getITSystemsResponse, error) {
	req := &graphql.Request{
		OpName: "getITSystems",
		Query: `
query getITSystems {
	itsystems {
		name
		system_type
		type
		user_key
		uuid
	}
}
`,
	}
	var err error

	var data getITSystemsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		nil,
		req,
		resp,
	)

	return &data, err
}
